Work Done Pull Request
sulaimonaa/Portfolio pull request #3
Opened 2023-03-27 10:23 UTC by sulaimonaa

Work and Skill list Update

2023-03-27 11:02 UTC, IngDavidTM requested changes
## Hi @sulaimonaa  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [ ] You've done a great job with the styling of the buttons within your portfolio! :+1: However, as a project requirement, it's important that the buttons follow the specified styling guidelines for the "Active", "Hover", and "Pressed" states. This will help to ensure consistency across the page and make the buttons more user-friendly and interactive.

![Screenshot from 2023-03-27 06-02-30](https://user-images.githubusercontent.com/105117832/227923748-e3b821d3-047c-47e0-becf-733c3c17003e.png)


- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 11:02 UTC, IngDavidTM commented on style.css
> +  }
- [ ] Great job on your page layout, :+1: but it's important to note that as a project requirement, the main container of the "works" section should have a `display:grid` property. This is necessary to ensure that the section follows the required specifications and can be properly displayed on different devices. Please ensure that you make the necessary adjustments to meet this requirement :+1:.

2023-03-27 11:02 UTC, IngDavidTM commented on index.html
> +                    <button class="lang_list">JavaScript</button>
- [ ] You have done an excellent job creating the list of project technologies, such as "JavaScript" and "HTML" :+1:. However, for better semantic structure, it's recommended that the list be organized using an unordered list (`ul`) with each technology item listed as a list item (`li`). This will help to ensure proper accessibility and readability of the list, and make it easier for users to navigate through the technologies :+1:.

2023-03-27 11:02 UTC, IngDavidTM commented on index.html
> +        <div class="about_title">About Myself</div>
- [ ] Great work on your project! :+1: However, for better semantic structure, it's recommended to use heading elements (e.g., `h1`, `h2`, etc.) instead of div elements for titles, such as "About Myself". Specifically, it's essential to choose the appropriate heading level (`h1` being the highest and `h6` being the lowest) to reflect the importance and hierarchy of the title on the page. This will help to improve accessibility and make it easier for users to navigate through the content.

2023-03-27 11:02 UTC, IngDavidTM commented on index.html
> +        </div>
- [ ] Kindly change the `div` element to a `p` element for the paragraph that begins with "Hello I'm a software...". This will improve the semantic structure of the content, as `p` elements are meant to represent paragraphs of text :+1:.

2023-03-27 11:02 UTC, IngDavidTM commented on index.html
>          <p class="connect_social"><a href="#">LET’S CONNECT</a></p>
- [ ] Kindly use an `hx` element instead of a `p` element as it is a title :+1:.

2023-03-27 11:02 UTC, IngDavidTM commented on index.html
> +        </section>
- [ ] Great work on creating the technology categories ("Languages", "Frameworks", and "Skills") on your page! :+1: However, for better semantic structure, it's recommended that these categories be placed within a `ul` element, with each category being represented by a separate `li` element. Additionally, the technologies listed within each category (such as "JavaScript", "HTML", and "CSS") should also be represented by a `ul` element with each technology being listed as a separate `li` element. This will help to improve the structure of the content and make it easier for users to understand and navigate through the information on the page :+1:.

2023-03-27 14:06 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @sulaimonaa 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

The Pull Request follows the GitHub Flow ✅
The PR title and description are professional and descriptive ✅
Linters are working properly ✅

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 14:15 UTC, merged

2023-04-27 12:48 UTC, TadesseDev reviewed
### Hi @sulaimonaa 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights

## Optional suggestions
- [Optional] Please try to be more descriptive in your pull request sumery. This is a place where you can introduce what changes you have made since the last merge. You can also specify any information that you would like to communicate with the code reviewer of the project.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._